server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index login.html;

    # Halaman default diarahkan ke katalog buku
    location = / {
        return 302 /index.html;
    }

    # Cache aset statis
    location /assets/ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /login.html;
}
