name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ vars.DOCKER_PASSWORD }}

      - name: Build Backend
        run: |
          docker build \
            -t ${{ vars.DOCKER_USERNAME }}/perpustakaan-backend:v1 \
            ./backend

      - name: Push Backend
        run: |
          docker push \
            ${{ vars.DOCKER_USERNAME }}/perpustakaan-backend:v1

      - name: Build Frontend
        run: |
          docker build \
            -t ${{ vars.DOCKER_USERNAME }}/perpustakaan-frontend:v1 \
            ./frontend

      - name: Push Frontend
        run: |
          docker push \
            ${{ vars.DOCKER_USERNAME }}/perpustakaan-frontend:v1


  deploy:
    name: Deploy to VM
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USER }}
          key: ${{ vars.VM_SSH_PRIVATE_KEY }}
          port: ${{ vars.VM_SSH_PORT || 22 }}

          script: |
            cd /opt/perpustakaan-digital

            docker pull ${{ vars.DOCKER_USERNAME }}/perpustakaan-backend:v1
            docker pull ${{ vars.DOCKER_USERNAME }}/perpustakaan-frontend:v1

            docker compose -f docker-compose.prod.yml up -d

            echo "Deploy v1 berhasil!"
